services:
  personal-website:
    container_name: personal-website
    build: .
    environment:
      NGINX_SERVER_NAME: "127.0.0.1"
    ports:
      - "127.0.0.1:80:80" # Redirects to 443
      - "127.0.0.1:443:443"
    volumes:
      - personal-website-ssl:/etc/ssl/personal-website/
      - default-server-ssl:/etc/ssl/default-server/
      - ./public/public/:/usr/share/personal-website/html/public/
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    restart: unless-stopped

volumes:
  personal-website-ssl:
  default-server-ssl:
