# Bridge networking

services:
  personal-website:
    container_name: personal-website
    build:
      args:
        - SET_CAP_NET_BIND_SERVICE=false # Not required when using bridge networking
    environment:
      NGINX_SERVER_NAME: "example.com"
      REALIP_FROM_CLOUDFLARE: "false" # Won't work when Docker isn't using host networking
      NGINX_HTTP_LISTEN_PORT: 80
      NGINX_HTTPS_LISTEN_PORT: 443
      NGINX_IPV4_LISTEN_ADDR: "0.0.0.0"
      NGINX_IPV6_LISTEN_ADDR: "[::]"
    ports:
      - "80:80" # Redirects to 443
      - "443:443"
    volumes:
      - personal-website-ssl:/etc/ssl/personal-website/
      - default-server-ssl:/etc/ssl/default-server/
      - ./public/public/:/usr/share/personal-website/html/public/
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    restart: unless-stopped

volumes:
  personal-website-ssl:
  default-server-ssl:
