services:
  personal-website:
    container_name: personal-website
    build: .
    ports:
      - "127.0.0.1:80:80" # Redirects to 443
      - "127.0.0.1:443:443"
    volumes:
      - personal-website-ssl:/etc/ssl/personal-website
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    restart: unless-stopped

volumes:
  personal-website-ssl:
